apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: basic-test-mount-spc
spec:
  provider: aws   
  secretObjects:
  - secretName: secrets-manager-json
    type: Opaque
    data:
    - objectName: secretsManagerUsername
      key: username
    - objectName: secretsManagerPassword
      key: password  

  parameters:
    objects: |     
        - objectName: "prod/service/token"
          objectType: "secretsmanager"
          jmesPath:
              - Path: "username"
                ObjectAlias: "secretsManagerUsername"
              - Path: "password"
                ObjectAlias: "secretsManagerPassword"
