name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: get current date
      id: date
      run: echo "::set-output name=date::$(date +'%s')"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag reg.mevijay.com/library/git-img-name:${{ steps.date.outputs.date }}
    - name: login to reg.mevijay
      uses: docker/login-action@v1
      with:
        registry: reg.mevijay.com
        username: ${{ secrets.REGNAME }}
        password: ${{ secrets.REGPASS }}
    - name: push image
      run: docker push reg.mevijay.com/library/git-img-name:${{ steps.date.outputs.date }}
