---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-demo
  region: us-east-2
  version: "1.21"
availabilityZones:
- us-east-2a
- us-east-2b
managedNodeGroups:
- name: general
  labels:
    role: general
  instanceType: t3.small
  minSize: 1
  maxSize: 10
  desiredCapacity: 1
  volumeSize: 20
